### model
model_name_or_path: /data/workspace/models/Baichuan2-13B-Chat

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: W_pack

### dataset
dataset: nl2sql_train
template: baichuan2
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/baichuan2-13b/nl2sql/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 0.00002
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

### eval
val_size: 0.1
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 500

# CUDA_VISIBLE_DEVICES=4 llamafactory-cli train examples/lora_single_gpu/baichuan2-13b-nl2sql_lora_sft.yaml
